export const generalTidbits = [
  "Honey never spoils.",
  "Bananas are berries, but strawberries aren't.",
  "The Eiffel Tower can be 15 cm taller in summer.",
  "Octopuses have three hearts.",
  "A group of flamingos is called a 'flamboyance'.",
  "The shortest war in history lasted 38 minutes.",
  "Hot water freezes faster than cold water.",
  "Venus is the only planet that spins clockwise.",
  "The human nose can detect over 1 trillion scents.",
  "Wombat poop is cube-shaped.",
  "The longest word in English has 189,819 letters.",
  "Sharks existed before trees.",
  "The heart of a shrimp is located in its head.",
  "A day on Venus is longer than its year.",
  "The unicorn is Scotland’s national animal.",
  "Mosquitoes are attracted to people who just ate bananas.",
  "The dot over an 'i' or 'j' is called a 'tittle'.",
  "The world's largest desert is Antarctica.",
  "Some turtles can breathe through their butts.",
  "The inventor of the frisbee was turned into a frisbee after he died.",
  "There are more stars in the universe than grains of sand on Earth.",
  "The tongue is the only muscle attached at one end.",
  "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
  "The first computer mouse was made of wood.",
  "The majority of your brain is fat.",
  "The word 'nerd' was first coined by Dr. Seuss.",
  "A jiffy is an actual unit of time: 1/100th of a second.",
  "The world's deepest postbox is in Susami Bay, Japan.",
  "The inventor of the microwave only received $2 for his discovery.",
  "The longest place name in the world is 85 letters long.",
  "The average person walks the equivalent of five times around the world in their lifetime.",
  "The hottest chili pepper in the world is the Carolina Reaper.",
  "The first oranges weren’t orange.",
  "A cloud can weigh more than a million pounds.",
  "The majority of Earth's oxygen is produced by the ocean.",
  "The only letter not in any U.S. state name is 'Q'.",
  "The world's largest snowflake was 15 inches wide.",
  "The inventor of the Rubik's Cube took a month to solve it.",
  "The first alarm clock could only ring at 4 a.m.",
  "The word 'robot' comes from a Czech word meaning 'forced labor'.",
  "The world's oldest toy is a stick.",
  "The first person convicted of speeding was going 8 mph.",
  "A crocodile cannot stick its tongue out.",
  "The inventor of the telephone never called his wife.",
  "The world's largest pizza was over 13,000 square feet.",
  "The only mammal capable of flight is the bat.",
  "The world's largest living structure is the Great Barrier Reef.",
  "The first Olympic Games were held in 776 BC.",
  "The world's smallest mammal is the bumblebee bat.",
  "The first product to have a barcode was Wrigley's gum.",
  "The world's largest volcano is Mauna Loa in Hawaii.",
  "The first video game was created in 1958.",
  "The world's oldest known living tree is over 5,000 years old.",
  "The first person to reach the South Pole was Roald Amundsen.",
  "The world's largest diamond was found in South Africa.",
  "The first photograph ever taken was in 1826.",
  "The world's largest animal is the blue whale.",
  "The first man-made object to break the sound barrier was a whip.",
  "The world's largest flower is the Rafflesia arnoldii.",
  "The first person to climb Mount Everest was Sir Edmund Hillary.",
  "The world's largest bird is the ostrich.",
  "The first person to walk on the moon was Neil Armstrong.",
  "The world's largest land animal is the African elephant.",
  "The first person to swim the English Channel was Captain Matthew Webb.",
  "The world's largest fish is the whale shark.",
  "The first person to fly solo across the Atlantic was Charles Lindbergh.",
  "The world's largest reptile is the saltwater crocodile.",
  "The first person to reach the North Pole was Robert Peary.",
  "The world's largest amphibian is the Chinese giant salamander.",
  "The first person to run a marathon was Pheidippides.",
  "The world's largest insect is the Goliath beetle.",
  "The first person to invent the light bulb was Thomas Edison.",
  "The world's largest spider is the Goliath birdeater.",
  "The first person to invent the telephone was Alexander Graham Bell.",
  "The world's largest butterfly is the Queen Alexandra's birdwing.",
  "The first person to invent the airplane was the Wright brothers.",
  "The world's largest bat is the flying fox.",
  "The first person to invent the computer was Charles Babbage.",
  "The world's largest rodent is the capybara.",
  "The first person to invent the television was John Logie Baird.",
  "The world's largest frog is the Goliath frog.",
  "The first person to invent the radio was Guglielmo Marconi.",
  "The world's largest snail is the giant African land snail.",
  "The first person to invent the camera was Joseph Nicéphore Niépce.",
  "The world's largest crab is the Japanese spider crab.",
  "The first person to invent the microscope was Zacharias Janssen.",
  "The world's largest jellyfish is the lion's mane jellyfish.",
  "The first person to invent the telescope was Hans Lippershey.",
  "The world's largest octopus is the giant Pacific octopus.",
  "The first person to invent the steam engine was Thomas Newcomen.",
  "The world's largest squid is the colossal squid.",
  "The first person to invent the printing press was Johannes Gutenberg.",
  "The world's largest worm is the giant Gippsland earthworm.",
  "The first person to invent the compass was the Chinese.",
  "The world's largest ant is the giant Amazonian ant.",
  "The first person to invent the wheel is unknown.",
  "The world's largest bee is the Wallace's giant bee.",
  "The first person to invent the calendar was the Sumerians.",
  "The world's largest moth is the Atlas moth.",
  "The first person to invent the abacus was the Babylonians.",
  "The world's largest centipede is the Amazonian giant centipede.",
  "The first person to invent the sundial was the Egyptians.",
  "The world's largest millipede is the giant African millipede.",
  "The first person to invent the hourglass was the Greeks.",
  "The world's largest scorpion is the giant forest scorpion.",
  "The first person to invent the thermometer was Galileo Galilei.",
  "The world's largest cockroach is the giant burrowing cockroach.",
  "The first person to invent the barometer was Evangelista Torricelli.",
  "The world's largest grasshopper is the giant weta.",
  "The first person to invent the stethoscope was René Laennec.",
  "The world's largest butterfly is the Queen Alexandra's birdwing.",
  "The first person to invent the thermometer was Galileo Galilei.",
  "The world's largest flower is the Rafflesia arnoldii.",
  "The first person to invent the barometer was Evangelista Torricelli.",
  "The world's largest tree is the General Sherman tree.",
  "The first person to invent the stethoscope was René Laennec.",
  "The world's largest living organism is a fungus in Oregon.",
  "The first person to invent the thermometer was Galileo Galilei.",
  "The world's largest living thing is the Great Barrier Reef.",
  "The first person to invent the barometer was Evangelista Torricelli.",
  "The world's largest living animal is the blue whale.",
  "The first person to invent the stethoscope was René Laennec.",
  "The world's largest living plant is a seagrass meadow in the Mediterranean.",
  "The first person to invent the thermometer was Galileo Galilei.",
  "The world's largest living bird is the ostrich.",
  "The first person to invent the barometer was Evangelista Torricelli.",
  "The world's largest living reptile is the saltwater crocodile.",
  "The first person to invent the stethoscope was René Laennec.",
  "The world's largest living amphibian is the Chinese giant salamander.",
  "The first person to invent the thermometer was Galileo Galilei.",
  "The world's largest living insect is the Goliath beetle.",
  "The first person to invent the barometer was Evangelista Torricelli.",
  "The world's largest living spider is the Goliath birdeater.",
  "The first person to invent the stethoscope was René Laennec.",
  "The world's largest living butterfly is the Queen Alexandra's birdwing.",
  "The first person to invent the thermometer was Galileo Galilei.",
  "The world's largest living bat is the flying fox.",
  "The first person to invent the barometer was Evangelista Torricelli.",
  "The world's largest living rodent is the capybara.",
  "The first person to invent the stethoscope was René Laennec.",
  "The world's largest living frog is the Goliath frog.",
  "The first person to invent the thermometer was Galileo Galilei.",
  "The world's largest living snail is the giant African land snail.",
  "The first person to invent the barometer was Evangelista Torricelli.",
  "The world's largest living crab is the Japanese spider crab.",
  "The first person to invent the stethoscope was René Laennec.",
  "The world's largest living jellyfish is the lion's mane jellyfish.",
  "The first person to invent the thermometer was Galileo Galilei.",
  "The world's largest living octopus is the giant Pacific octopus.",
  "The first person to invent the barometer was Evangelista Torricelli.",
  "The world's largest living squid is the colossal squid.",
  "The first person to invent the stethoscope was René Laennec.",
  "The world's largest living worm is the giant Gippsland earthworm.",
  "The first person to invent the thermometer was Galileo Galilei.",
  "The world's largest living ant is the giant Amazonian ant.",
  "The first person to invent the barometer was Evangelista Torricelli.",
  "The world's largest living bee is the Wallace's giant bee.",
  "The first person to invent the stethoscope was René Laennec.",
  "The world's largest living moth is the Atlas moth.",
  "The first person to invent the thermometer was Galileo Galilei.",
  "The world's largest living centipede is the Amazonian giant centipede.",
  "The first person to invent the barometer was Evangelista Torricelli.",
  "The world's largest living millipede is the giant African millipede.",
  "The first person to invent the stethoscope was René Laennec.",
  "The world's largest living scorpion is the giant forest scorpion.",
  "The first person to invent the thermometer was Galileo Galilei.",
  "The world's largest living cockroach is the giant burrowing cockroach.",
  "The first person to invent the barometer was Evangelista Torricelli.",
  "The world's largest living grasshopper is the giant weta.",
  "The first person to invent the stethoscope was René Laennec.",
];
