# File locations
csv_file = "datasets/1000_dataset.csv"
lexicon_file = "indexes/lexicon.csv"
forward_index_folder = 'indexes/forward'
inverted_index_folder = 'indexes/inverted'
id_file = 'indexes/latest_id.txt'
doc_id_file = 'indexes/latest_doc_id.txt'
processed_file = 'indexes/processed.csv'
scrapped_file = 'indexes/scraped.csv'
received_file = 'received.csv'
lengths_file = 'indexes/lengths.csv'