# Use official Python image as base
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY requirements.txt .
COPY indexes/lexicon.csv /app/indexes/lexicon.csv
COPY indexes/processed.csv /app/indexes/processed.csv
COPY indexes/lengths.csv /app/indexes/lengths.csv
COPY indexes/scraped.csv /app/indexes/scraped.csv

RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose the port your app will run on
EXPOSE 8000

# Command to run your app
CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "8000"]
