# fly.toml app configuration file generated for spillage-search-ancient-frog-4456 on 2025-08-22T22:54:02+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spillage-search-ancient-frog-4456'
primary_region = 'sin'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
