app = "spillage-search"

[build]
  dockerfile = "Dockerfile"  # Path to the Dockerfile (for backend)

[[services]]
  internal_port = 8000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  [services.ports]
    http = 80
    https = 443
    internal_port = 8000
