# fly.toml app configuration file generated for spillage-search-floral-morning-2392 on 2024-12-22T04:09:34+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spillage-search-floral-morning-2392'
primary_region = 'syd'

[build]
  dockerfile = 'DockerFile'

[[services]]
protocol = 'tcp'
internal_port = 8000

[[services.ports]]
port = 80

[services.concurrency]
  type = 'connections'
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
